Excel Format with Using Pandas Operations

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\H6jyo\AppData\Roaming\Python\Python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\H6jyo\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\H6jyo\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\H6jyo\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\H6jyo\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\H6jyo\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

df = pd.read_excel("Employee_Performance_Data.xlsx")
df.head()

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
0,EMP1088,Jennifer Ramirez,NaN,NaN,2018,41090.0,NaN,2.0,4.0,79.6,2.4,19.0
1,EMP1126,Karen Ramirez,Engineering,38.0,2016,40240.0,7.6,19.0,99.0,93.6,4.6,2.0
2,EMP1045,Jessica Gonzalez,Sales,37.0,2016,41949.0,8.6,4.0,96.0,83.4,4.5,39.0
3,EMP1011,Sandra Garcia,Marketing,51.0,2023,147734.0,1.9,26.0,93.0,80.7,3.3,12.0
4,EMP1052,Lisa Smith,Engineering,58.0,2017,96886.0,9.3,21.0,77.0,90.8,1.6,40.0

In [4]:
print("\n Last 5 rows:")
df.tail()

 Last 5 rows:

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
148,EMP1142,William Rodriguez,Marketing,37.0,2019,117558.0,1.9,26.0,39.0,76.6,1.5,3.0
149,EMP1092,Margaret Harris,NaN,NaN,2016,93243.0,9.4,10.0,8.0,NaN,4.9,19.0
150,EMP1103,Barbara Robinson,Sales,57.0,2020,58954.0,8.4,11.0,86.0,82.1,NaN,17.0
151,EMP1067,Michelle Perez,Finance,37.0,2017,90479.0,5.8,3.0,6.0,NaN,4.9,33.0
152,EMP1025,Susan Moore,Sales,53.0,2020,59285.0,7.6,10.0,33.0,87.9,2.0,24.0

In [8]:
print("Shape:",df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nDataTypes :")
print(df.dtypes)

print("Information of Dataset:")
df.info()
df.size

Shape: (153, 12)

Columns:
['EmployeeID', 'Name', 'Department', 'Age', 'JoinYear', 'Salary', 'PerformanceScore', 'ProjectsCompleted', 'TrainingHours', 'AttendancePct', 'SatisfactionScore', 'OvertimeHours']

DataTypes :
EmployeeID            object
Name                  object
Department            object
Age                  float64
JoinYear               int64
Salary               float64
PerformanceScore     float64
ProjectsCompleted    float64
TrainingHours        float64
AttendancePct        float64
SatisfactionScore    float64
OvertimeHours        float64
dtype: object
Information of Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         153 non-null    object
 1   Name               139 non-null    object
 2   Department         141 non-null    object
 3   Age                139 non-null    float64
 4   JoinYear           153 non-null    int64
 5   Salary             138 non-null    float64
 6   PerformanceScore   139 non-null    float64
 7   ProjectsCompleted  137 non-null    float64
 8   TrainingHours      143 non-null    float64
 9   AttendancePct      143 non-null    float64
 10  SatisfactionScore  138 non-null    float64
 11  OvertimeHours      143 non-null    float64
dtypes: float64(8), int64(1), object(3)
memory usage: 14.5+ KB

1836

In [ ]:
import numpy as np

print("Summary Statistics:")
display(df.select_dtypes(include=[np.number]).describe())
print("\n Unique Values in Department:")
print(df["Department"].unique())

print("\n Department Counts:")
print(df["Department"].value_counts(dropna=False))

Summary Statistics:

,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
count,139.000000,153.000000,138.000000,139.000000,137.000000,143.000000,143.000000,138.000000,143.000000
mean,41.985612,2019.549020,92069.369565,5.607914,15.014599,49.209790,85.727273,3.111594,24.783217
std,10.822672,2.969009,33891.427372,2.434417,8.399917,30.468144,9.077927,1.215296,13.833588
min,22.000000,2015.000000,35055.000000,1.000000,0.000000,0.000000,70.500000,1.000000,1.000000
25%,33.000000,2017.000000,59697.250000,4.000000,8.000000,23.500000,77.700000,2.000000,12.000000
50%,43.000000,2019.000000,90436.000000,5.800000,16.000000,50.000000,86.200000,3.450000,24.000000
75%,51.500000,2022.000000,119995.750000,7.600000,22.000000,77.000000,93.850000,4.175000,36.500000
max,58.000000,2024.000000,149937.000000,10.000000,29.000000,99.000000,99.900000,5.000000,49.000000

 Unique Values in Department:
[nan 'Engineering' 'Sales' 'Marketing' 'Customer Support' 'HR' 'Finance'
 'Operations']

 Department Counts:
Department
Sales               25
Operations          24
Marketing           21
Engineering         19
Finance             18
HR                  17
Customer Support    17
NaN                 12
Name: count, dtype: int64

In [10]:
print("One column:")
display(df["PerformanceScore"])

print("Multiple Columns:")
display(df[["Name","Department","PerformanceScore"]])

One column:

0      NaN
1      7.6
2      8.6
3      1.9
4      9.3
      ...
148    1.9
149    9.4
150    8.4
151    5.8
152    7.6
Name: PerformanceScore, Length: 153, dtype: float64

Multiple Columns:

                  Name   Department  PerformanceScore
0     Jennifer Ramirez          NaN               NaN
1        Karen Ramirez  Engineering               7.6
2     Jessica Gonzalez        Sales               8.6
3        Sandra Garcia    Marketing               1.9
4           Lisa Smith  Engineering               9.3
..                 ...          ...               ...
148  William Rodriguez    Marketing               1.9
149    Margaret Harris          NaN               9.4
150   Barbara Robinson        Sales               8.4
151     Michelle Perez      Finance               5.8
152        Susan Moore        Sales               7.6

[153 rows x 3 columns]

In [11]:
print("First Row:")
display(df.loc[0])

print("Specific values:")
print(df.loc[0,"PerformanceScore"])

print("Selected rows and columns:")
display(df.loc[0:4,["Name","PerformanceScore"]])

First Row:

EmployeeID                    EMP1088
Name                 Jennifer Ramirez
Department                        NaN
Age                               NaN
JoinYear                         2018
Salary                        41090.0
PerformanceScore                  NaN
ProjectsCompleted                 2.0
TrainingHours                     4.0
AttendancePct                    79.6
SatisfactionScore                 2.4
OvertimeHours                    19.0
Name: 0, dtype: object

Specific values:
nan
Selected rows and columns:

               Name  PerformanceScore
0  Jennifer Ramirez               NaN
1     Karen Ramirez               7.6
2  Jessica Gonzalez               8.6
3     Sandra Garcia               1.9
4        Lisa Smith               9.3

In [12]:
print("First Row:")
display(df.iloc[0])

print("First 5 rows ,first 4 columns:")
display(df.iloc[0:5,0:4])

First Row:

EmployeeID                    EMP1088
Name                 Jennifer Ramirez
Department                        NaN
Age                               NaN
JoinYear                         2018
Salary                        41090.0
PerformanceScore                  NaN
ProjectsCompleted                 2.0
TrainingHours                     4.0
AttendancePct                    79.6
SatisfactionScore                 2.4
OvertimeHours                    19.0
Name: 0, dtype: object

First 5 rows ,first 4 columns:

  EmployeeID              Name   Department   Age
0    EMP1088  Jennifer Ramirez          NaN   NaN
1    EMP1126     Karen Ramirez  Engineering  38.0
2    EMP1045  Jessica Gonzalez        Sales  37.0
3    EMP1011     Sandra Garcia    Marketing  51.0
4    EMP1052        Lisa Smith  Engineering  58.0

In [17]:
print("Employees with PerformanceScore > 9.5")
display(df[df["PerformanceScore"]>9.5])

print("Employees with Attendance >=98:")
display(df[df["AttendancePct"]>=98])

Employees with PerformanceScore > 9.5

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
33,EMP1049,Donald Anderson,Finance,57.0,2023,41941.0,10.0,27.0,34.0,92.0,3.7,NaN
59,EMP1054,David Jackson,Engineering,31.0,2015,118251.0,9.8,28.0,45.0,77.5,4.5,29.0
110,EMP1133,Michelle Smith,Customer Support,33.0,2015,39432.0,10.0,28.0,75.0,75.0,2.9,6.0
111,EMP1093,Kenneth Robinson,Operations,29.0,2019,145951.0,9.9,5.0,97.0,70.7,NaN,15.0

Employees with Attendance >=98:

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
26,EMP1070,Joshua Anderson,Operations,53.0,2023,54963.0,NaN,24.0,84.0,98.3,3.5,48.0
40,EMP1017,Mark Clark,Sales,58.0,2022,NaN,5.8,7.0,7.0,98.1,4.8,17.0
42,EMP1120,NaN,NaN,33.0,2019,147428.0,5.8,27.0,36.0,99.6,2.7,17.0
45,EMP1125,Donald Williams,HR,51.0,2015,57574.0,4.0,16.0,NaN,98.5,2.6,40.0
56,EMP1100,Joshua Smith,Marketing,25.0,2019,110697.0,NaN,16.0,73.0,99.9,3.0,NaN
66,EMP1098,NaN,Marketing,55.0,2023,68434.0,1.4,1.0,23.0,98.2,1.1,2.0
77,EMP1058,Robert Martinez,HR,52.0,2020,132239.0,7.5,21.0,53.0,98.3,2.3,21.0
84,EMP1130,Ashley Miller,Marketing,34.0,2019,145698.0,5.5,21.0,16.0,98.3,3.6,28.0
87,EMP1057,Paul Clark,HR,55.0,2015,91800.0,8.4,8.0,36.0,99.6,1.5,25.0
93,EMP1134,David Ramirez,Operations,40.0,2019,130257.0,7.8,7.0,NaN,99.7,4.9,11.0
100,EMP1107,Thomas Clark,Finance,31.0,2023,NaN,9.2,23.0,13.0,99.5,2.8,12.0
107,EMP1147,David Taylor,Marketing,42.0,2019,108686.0,5.5,28.0,9.0,99.1,NaN,49.0
119,EMP1098,NaN,Marketing,55.0,2023,68434.0,1.4,1.0,23.0,98.2,1.1,2.0
132,EMP1069,James Williams,Sales,49.0,2018,122369.0,7.9,22.0,22.0,99.1,2.0,43.0
142,EMP1136,Matthew Robinson,Sales,30.0,2020,114104.0,8.0,6.0,84.0,98.3,4.5,29.0

In [18]:
res = df [
    (df["PerformanceScore"]>90) |
    (df["AttendancePct"]>=99)
]
display(res)
print("Sales or HR Employees:")
display(df[df["Department"].isin(["Sales","HR"])])

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
42,EMP1120,NaN,NaN,33.0,2019,147428.0,5.8,27.0,36.0,99.6,2.7,17.0
56,EMP1100,Joshua Smith,Marketing,25.0,2019,110697.0,NaN,16.0,73.0,99.9,3.0,NaN
87,EMP1057,Paul Clark,HR,55.0,2015,91800.0,8.4,8.0,36.0,99.6,1.5,25.0
93,EMP1134,David Ramirez,Operations,40.0,2019,130257.0,7.8,7.0,NaN,99.7,4.9,11.0
100,EMP1107,Thomas Clark,Finance,31.0,2023,NaN,9.2,23.0,13.0,99.5,2.8,12.0
107,EMP1147,David Taylor,Marketing,42.0,2019,108686.0,5.5,28.0,9.0,99.1,NaN,49.0
132,EMP1069,James Williams,Sales,49.0,2018,122369.0,7.9,22.0,22.0,99.1,2.0,43.0

Sales or HR Employees:

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
2,EMP1045,Jessica Gonzalez,Sales,37.0,2016,41949.0,8.6,4.0,96.0,83.4,4.5,39.0
6,EMP1115,Ashley Thompson,HR,53.0,2015,NaN,NaN,16.0,25.0,78.6,2.1,28.0
7,EMP1066,Andrew Lopez,Sales,NaN,2018,149825.0,7.6,13.0,73.0,90.9,3.5,14.0
16,EMP1084,Donald Brown,Sales,50.0,2022,NaN,2.1,24.0,66.0,72.0,NaN,NaN
18,EMP1145,Karen White,Sales,33.0,2017,43717.0,5.1,NaN,52.0,80.5,3.5,19.0
19,EMP1129,Charles Martin,HR,43.0,2015,90645.0,8.9,19.0,33.0,96.4,1.1,34.0
20,EMP1065,Lisa Jones,HR,37.0,2019,74811.0,2.8,25.0,6.0,71.0,NaN,49.0
22,EMP1075,NaN,Sales,56.0,2019,49388.0,4.3,7.0,59.0,94.9,NaN,8.0
34,EMP1022,William Miller,HR,22.0,2016,77944.0,6.8,14.0,9.0,87.9,1.3,31.0
36,EMP1102,Ashley White,Sales,50.0,2017,46314.0,8.2,26.0,58.0,NaN,3.7,10.0
37,EMP1121,Nancy Hernandez,HR,34.0,2024,116818.0,NaN,17.0,74.0,82.8,3.6,18.0
40,EMP1017,Mark Clark,Sales,58.0,2022,NaN,5.8,7.0,7.0,98.1,4.8,17.0
41,EMP1101,Lisa Anderson,Sales,32.0,2018,63732.0,7.8,10.0,29.0,80.5,4.1,13.0
45,EMP1125,Donald Williams,HR,51.0,2015,57574.0,4.0,16.0,NaN,98.5,2.6,40.0
49,EMP1118,Thomas Garcia,Sales,53.0,2016,143464.0,4.2,21.0,97.0,71.3,2.7,17.0
57,EMP1076,Joseph Anderson,HR,54.0,2020,40569.0,5.1,14.0,81.0,71.1,4.9,5.0
61,EMP1026,William Sanchez,Sales,46.0,2017,NaN,NaN,11.0,96.0,80.0,3.9,32.0
68,EMP1015,Nancy Lewis,Sales,49.0,2020,93017.0,8.6,29.0,3.0,84.3,1.5,17.0
69,EMP1053,Linda White,HR,44.0,2023,110745.0,1.0,18.0,31.0,95.5,4.5,12.0
73,EMP1122,Jessica Smith,Sales,NaN,2023,58624.0,3.1,20.0,69.0,81.5,2.6,21.0
75,EMP1113,Mary Lee,Sales,57.0,2021,139680.0,9.1,23.0,21.0,73.3,3.7,44.0
77,EMP1058,Robert Martinez,HR,52.0,2020,132239.0,7.5,21.0,53.0,98.3,2.3,21.0
81,EMP1018,Margaret Ramirez,HR,NaN,2024,84922.0,3.1,5.0,28.0,NaN,4.4,45.0
82,EMP1050,James Harris,HR,54.0,2021,60934.0,NaN,25.0,95.0,94.2,3.5,32.0
85,EMP1081,Sandra Jones,Sales,22.0,2024,80002.0,1.8,NaN,19.0,90.9,4.7,NaN
87,EMP1057,Paul Clark,HR,55.0,2015,91800.0,8.4,8.0,36.0,99.6,1.5,25.0
92,EMP1027,Mary Martin,HR,22.0,2022,77808.0,6.3,25.0,86.0,93.1,3.0,37.0
95,EMP1119,Lisa Jones,HR,NaN,2015,126865.0,4.5,25.0,86.0,70.5,4.8,5.0
113,EMP1016,NaN,HR,47.0,2021,96877.0,1.8,9.0,0.0,89.9,4.6,29.0
116,EMP1048,Anthony Ramirez,Sales,NaN,2022,108553.0,7.3,16.0,33.0,96.2,3.8,32.0
118,EMP1146,Paul White,HR,46.0,2015,63699.0,6.4,29.0,70.0,71.7,NaN,23.0
124,EMP1004,Charles Thompson,Sales,25.0,2024,56949.0,7.2,26.0,18.0,75.0,3.8,37.0
131,EMP1056,NaN,Sales,57.0,2022,88413.0,7.5,7.0,67.0,76.6,4.3,12.0
132,EMP1069,James Williams,Sales,49.0,2018,122369.0,7.9,22.0,22.0,99.1,2.0,43.0
134,EMP1019,Jessica Anderson,Sales,44.0,2023,129074.0,4.1,5.0,54.0,NaN,4.2,46.0
135,EMP1006,Lisa Lee,Sales,53.0,2024,72744.0,7.7,18.0,0.0,72.5,4.3,21.0
136,EMP1055,Thomas Davis,Sales,26.0,2023,129456.0,5.4,13.0,15.0,84.7,1.1,32.0
137,EMP1075,NaN,Sales,56.0,2019,49388.0,4.3,7.0,59.0,94.9,NaN,8.0
138,EMP1000,Kenneth Martin,HR,NaN,2023,80106.0,7.5,3.0,92.0,82.6,5.0,43.0
142,EMP1136,Matthew Robinson,Sales,30.0,2020,114104.0,8.0,6.0,84.0,98.3,4.5,29.0
150,EMP1103,Barbara Robinson,Sales,57.0,2020,58954.0,8.4,11.0,86.0,82.1,NaN,17.0
152,EMP1025,Susan Moore,Sales,53.0,2020,59285.0,7.6,10.0,33.0,87.9,2.0,24.0

In [19]:
print("Highest Performance scores:")
display(df.sort_values("PerformanceScore",ascending=False).head(10))

print("Lowest Attendence :")
display(df.sort_values("AttendancePct",ascending=True).head(10))

Highest Performance scores:

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
33,EMP1049,Donald Anderson,Finance,57.0,2023,41941.0,10.0,27.0,34.0,92.0,3.7,NaN
110,EMP1133,Michelle Smith,Customer Support,33.0,2015,39432.0,10.0,28.0,75.0,75.0,2.9,6.0
111,EMP1093,Kenneth Robinson,Operations,29.0,2019,145951.0,9.9,5.0,97.0,70.7,NaN,15.0
59,EMP1054,David Jackson,Engineering,31.0,2015,118251.0,9.8,28.0,45.0,77.5,4.5,29.0
146,EMP1072,James Jones,Customer Support,41.0,2023,137468.0,9.4,21.0,NaN,95.9,4.1,10.0
149,EMP1092,Margaret Harris,NaN,NaN,2016,93243.0,9.4,10.0,8.0,NaN,4.9,19.0
98,EMP1096,Richard Rodriguez,Customer Support,31.0,2020,118807.0,9.3,17.0,98.0,96.2,4.0,21.0
4,EMP1052,Lisa Smith,Engineering,58.0,2017,96886.0,9.3,21.0,77.0,90.8,1.6,40.0
100,EMP1107,Thomas Clark,Finance,31.0,2023,NaN,9.2,23.0,13.0,99.5,2.8,12.0
112,EMP1031,Andrew Wilson,NaN,50.0,2015,54758.0,9.1,17.0,49.0,84.9,1.3,21.0

Lowest Attendence :

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
95,EMP1119,Lisa Jones,HR,NaN,2015,126865.0,4.5,25.0,86.0,70.5,4.8,5.0
79,EMP1095,Mark Robinson,Marketing,47.0,2018,76240.0,4.4,6.0,43.0,70.6,1.5,5.0
111,EMP1093,Kenneth Robinson,Operations,29.0,2019,145951.0,9.9,5.0,97.0,70.7,NaN,15.0
70,EMP1020,John Jones,Operations,30.0,2016,67049.0,5.3,7.0,2.0,70.9,3.6,NaN
20,EMP1065,Lisa Jones,HR,37.0,2019,74811.0,2.8,25.0,6.0,71.0,NaN,49.0
57,EMP1076,Joseph Anderson,HR,54.0,2020,40569.0,5.1,14.0,81.0,71.1,4.9,5.0
67,EMP1059,Kenneth Sanchez,Operations,31.0,2019,NaN,5.8,10.0,84.0,71.2,4.0,38.0
49,EMP1118,Thomas Garcia,Sales,53.0,2016,143464.0,4.2,21.0,97.0,71.3,2.7,17.0
52,EMP1003,Daniel Miller,NaN,26.0,2024,92091.0,2.2,NaN,NaN,71.4,4.0,8.0
147,EMP1023,Sarah Brown,Customer Support,22.0,2019,108963.0,5.3,25.0,73.0,71.5,2.6,10.0

In [23]:
work = df.copy()
work["Passed"] = work["PerformanceScore"]>=60
work["Total_Score"]= work["PerformanceScore"]+ work["SatisfactionScore"]
work["Average_Score"] = work[["PerformanceScore","SatisfactionScore"]].mean(axis=1)

display(work[["Name","PerformanceScore","SatisfactionScore","Total_Score","Average_Score","Passed"]].head(10))

,Name,PerformanceScore,SatisfactionScore,Total_Score,Average_Score,Passed
0,Jennifer Ramirez,NaN,2.4,NaN,2.40,False
1,Karen Ramirez,7.6,4.6,12.2,6.10,False
2,Jessica Gonzalez,8.6,4.5,13.1,6.55,False
3,Sandra Garcia,1.9,3.3,5.2,2.60,False
4,Lisa Smith,9.3,1.6,10.9,5.45,False
5,Betty Williams,2.5,1.9,4.4,2.20,False
6,Ashley Thompson,NaN,2.1,NaN,2.10,False
7,Andrew Lopez,7.6,3.5,11.1,5.55,False
8,Donald Moore,1.1,2.4,3.5,1.75,False
9,NaN,6.1,2.1,8.2,4.10,False

In [25]:
# Creating a feature with np.where()

work["Performance_level"] = np.where(
    work["PerformanceScore"]>=75,"Excellent",
    np.where(work["PerformanceScore"]>=60,"Good","Needs Improvement")
)
display(work[["Name","PerformanceScore","Performance_level"]].head(10))

               Name  PerformanceScore  Performance_level
0  Jennifer Ramirez               NaN  Needs Improvement
1     Karen Ramirez               7.6  Needs Improvement
2  Jessica Gonzalez               8.6  Needs Improvement
3     Sandra Garcia               1.9  Needs Improvement
4        Lisa Smith               9.3  Needs Improvement
5    Betty Williams               2.5  Needs Improvement
6   Ashley Thompson               NaN  Needs Improvement
7      Andrew Lopez               7.6  Needs Improvement
8      Donald Moore               1.1  Needs Improvement
9               NaN               6.1  Needs Improvement

In [26]:
#Rename Columns
renamed = df.rename(columns = {
    "PerformanceScore":"Final_Performance_Score",
    "TrainingHours": "Daily_Training_Hours"
})
display(renamed.head())

,EmployeeID,Name,Department,Age,JoinYear,Salary,Final_Performance_Score,ProjectsCompleted,Daily_Training_Hours,AttendancePct,SatisfactionScore,OvertimeHours
0,EMP1088,Jennifer Ramirez,NaN,NaN,2018,41090.0,NaN,2.0,4.0,79.6,2.4,19.0
1,EMP1126,Karen Ramirez,Engineering,38.0,2016,40240.0,7.6,19.0,99.0,93.6,4.6,2.0
2,EMP1045,Jessica Gonzalez,Sales,37.0,2016,41949.0,8.6,4.0,96.0,83.4,4.5,39.0
3,EMP1011,Sandra Garcia,Marketing,51.0,2023,147734.0,1.9,26.0,93.0,80.7,3.3,12.0
4,EMP1052,Lisa Smith,Engineering,58.0,2017,96886.0,9.3,21.0,77.0,90.8,1.6,40.0

In [27]:
#Cleaning of data
# Remove Columns and Rows
# axis = 1/columns -> Remove columns
# axis =0/index -> Remove Rows

example = work.drop(columns=["Total_Score"])
display(example.head())

example = work.drop(index=[0,1])
display(example.head())

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours,Passed,Average_Score,Performance_level
0,EMP1088,Jennifer Ramirez,NaN,NaN,2018,41090.0,NaN,2.0,4.0,79.6,2.4,19.0,False,2.40,Needs Improvement
1,EMP1126,Karen Ramirez,Engineering,38.0,2016,40240.0,7.6,19.0,99.0,93.6,4.6,2.0,False,6.10,Needs Improvement
2,EMP1045,Jessica Gonzalez,Sales,37.0,2016,41949.0,8.6,4.0,96.0,83.4,4.5,39.0,False,6.55,Needs Improvement
3,EMP1011,Sandra Garcia,Marketing,51.0,2023,147734.0,1.9,26.0,93.0,80.7,3.3,12.0,False,2.60,Needs Improvement
4,EMP1052,Lisa Smith,Engineering,58.0,2017,96886.0,9.3,21.0,77.0,90.8,1.6,40.0,False,5.45,Needs Improvement

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours,Passed,Total_Score,Average_Score,Performance_level
2,EMP1045,Jessica Gonzalez,Sales,37.0,2016,41949.0,8.6,4.0,96.0,83.4,4.5,39.0,False,13.1,6.55,Needs Improvement
3,EMP1011,Sandra Garcia,Marketing,51.0,2023,147734.0,1.9,26.0,93.0,80.7,3.3,12.0,False,5.2,2.60,Needs Improvement
4,EMP1052,Lisa Smith,Engineering,58.0,2017,96886.0,9.3,21.0,77.0,90.8,1.6,40.0,False,10.9,5.45,Needs Improvement
5,EMP1128,Betty Williams,Customer Support,46.0,2017,45478.0,2.5,16.0,NaN,82.5,1.9,9.0,False,4.4,2.20,Needs Improvement
6,EMP1115,Ashley Thompson,HR,53.0,2015,NaN,NaN,16.0,25.0,78.6,2.1,28.0,False,NaN,2.10,Needs Improvement

In [28]:
# Missing Val

print("Missing values by columns:")
print(df.isna().sum())

print("\n Total Missing Values:")
print(df.isna().sum().sum())

Missing values by columns:
EmployeeID            0
Name                 14
Department           12
Age                  14
JoinYear              0
Salary               15
PerformanceScore     14
ProjectsCompleted    16
TrainingHours        10
AttendancePct        10
SatisfactionScore    15
OvertimeHours        10
dtype: int64

 Total Missing Values:
130

In [29]:
#Remove rows  with missing values (dropna())

complete_rows = df.dropna()
print("Original shape:",df.shape)
print("After dropna:",complete_rows.shape)
display(complete_rows.head())

Original shape: (153, 12)
After dropna: (61, 12)

,EmployeeID,Name,Department,Age,JoinYear,Salary,PerformanceScore,ProjectsCompleted,TrainingHours,AttendancePct,SatisfactionScore,OvertimeHours
1,EMP1126,Karen Ramirez,Engineering,38.0,2016,40240.0,7.6,19.0,99.0,93.6,4.6,2.0
2,EMP1045,Jessica Gonzalez,Sales,37.0,2016,41949.0,8.6,4.0,96.0,83.4,4.5,39.0
3,EMP1011,Sandra Garcia,Marketing,51.0,2023,147734.0,1.9,26.0,93.0,80.7,3.3,12.0
4,EMP1052,Lisa Smith,Engineering,58.0,2017,96886.0,9.3,21.0,77.0,90.8,1.6,40.0
8,EMP1037,Donald Moore,Finance,43.0,2017,72441.0,1.1,10.0,66.0,90.8,2.4,31.0

In [30]:
# Fillna()  we can use mean,median,max,min

filled = df.copy()
filled["AttendancePct"]=filled["AttendancePct"].fillna(
    filled["AttendancePct"].median()
)
filled["TrainingHours"]=filled["TrainingHours"].fillna(
    filled["TrainingHours"].median()
)
filled["Department"]=filled["Department"].fillna("Unknown")

print("Remaining missing Values:")
print(filled.isna().sum())

Remaining missing Values:
EmployeeID            0
Name                 14
Department            0
Age                  14
JoinYear              0
Salary               15
PerformanceScore     14
ProjectsCompleted    16
TrainingHours         0
AttendancePct         0
SatisfactionScore    15
OvertimeHours        10
dtype: int64

In [31]:
#Forward Fill and Backward Fill

time_df = pd.DataFrame({
    "Day":[1,2,3,4,5],
    "Temperature":[30,np.nan,32,np.nan,35]
})
display(time_df)
print("Forward fill:")
display(time_df.ffill())
print("Backward Fill:")
display("time_df.bfill()")

   Day  Temperature
0    1         30.0
1    2          NaN
2    3         32.0
3    4          NaN
4    5         35.0

Forward fill:

   Day  Temperature
0    1         30.0
1    2         30.0
2    3         32.0
3    4         32.0
4    5         35.0

Backward Fill:

'time_df.bfill()'